// Re-export shared types for convenient imports within the web app
export type {
  ApiResponse,
  ApiSuccessResponse,
  ApiErrorResponse,
  PaginatedResponse,
  UserPublic,
  AuthTokens,
  AuthResponse,
  GroupType,
  MemberRole,
  GroupMemberPublic,
  GroupPublic,
  Priority,
  TaskStatus,
  TaskPublic,
  MessageType,
  MessageReactionPublic,
  MessagePublic,
  FilePublic,
  NotePublic,
  MeetingAttendancePublic,
  MeetingPublic,
  NotificationType,
  NotificationPublic,
  PeerEvaluationPublic,
  AiPromptPublic,
  AiSummaryPublic,
} from '@studysync/types';
