// API types
export type {
  ApiSuccessResponse,
  ApiErrorResponse,
  ApiResponse,
  PaginatedResponse,
  UserDTO,
  UserPublic,
  AuthTokens,
  AuthResponse,
  GroupType,
  MemberRole,
  GroupMemberPublic,
  GroupPublic,
  Priority,
  TaskStatus,
  TaskPublic,
  MessageType,
  MessageReactionPublic,
  MessagePublic,
  FilePublic,
  NotePublic,
  MeetingAttendancePublic,
  MeetingPublic,
  NotificationType,
  NotificationPublic,
  PeerEvaluationPublic,
  AiTaskAssignment,
  AiTaskDistributionResponse,
  AiAssignmentBreakdown,
  AiPromptPublic,
  AiSummaryPublic,
} from './api';

// Socket types
export type {
  ClientToServerEvents,
  ServerToClientEvents,
  InterServerEvents,
  SocketData,
} from './socket';

// Validation schemas and inferred types
export {
  registerSchema,
  loginSchema,
  updateProfileSchema,
  groupTypeSchema,
  createGroupSchema,
  updateGroupSchema,
  joinGroupSchema,
  prioritySchema,
  taskStatusSchema,
  createTaskSchema,
  updateTaskSchema,
  messageTypeSchema,
  sendMessageSchema,
  addReactionSchema,
  fileUploadSchema,
  createNoteSchema,
  updateNoteSchema,
  createMeetingSchema,
  updateMeetingSchema,
  createEvaluationSchema,
  aiAssistantSchema,
  paginationSchema,
} from './validation';

export type {
  RegisterInput,
  LoginInput,
  UpdateProfileInput,
  CreateGroupInput,
  UpdateGroupInput,
  JoinGroupInput,
  CreateTaskInput,
  UpdateTaskInput,
  SendMessageInput,
  AddReactionInput,
  FileUploadInput,
  CreateNoteInput,
  UpdateNoteInput,
  CreateMeetingInput,
  UpdateMeetingInput,
  CreateEvaluationInput,
  AiAssistantInput,
  PaginationInput,
} from './validation';
